server:
  port: 81
  servlet:
    context-path: /user
spring:
  application:
    name: user-service
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        namespace: dev
        server-addr: 127.0.0.1:8848
